{% set name = "amply" %}
{% set version = "0.1.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61421103ccf8e1066717115fe7917610d831d551c68d31a110876a5b6c78aea4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools_scm 7.1.0
  run:
    - python
    - docutils >=0.3
    - pyparsing

test:
  imports:
    - amply
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/willu47/amply
  summary: Amply allows you to load and manipulate AMPL/GLPK data as Python data structures
  description: | 
    Amply allows you to load and manipulate AMPL/GLPK data as Python data structures.
    Amply only supports a specific subset of the AMPL syntax: set declarations; set 
    data statements; parameter declarations; parameter data statements
  license: EPL-2.0
  license_file: LICENSE
  license_family: OTHER
  doc_url: https://github.com/willu47/amply/blob/master/README.rst
  dev_url: https://github.com/willu47/amply

extra:
  recipe-maintainers:
    - ocefpaf
